import type { CharacterCard, Condition, MarkerCategory } from "./types";

const min = (marker: MarkerCategory, count: number): Condition => ({
  type: "minCount",
  marker,
  count,
});

const max = (marker: MarkerCategory, count: number): Condition => ({
  type: "maxCount",
  marker,
  count,
});

const all = (...conditions: Condition[]): Condition => ({
  type: "allOf",
  conditions,
});

const last = (marker: MarkerCategory): Condition => ({
  type: "lastIs",
  marker,
});

export const CHARACTER_CARDS: CharacterCard[] = [
  {
    id: "botti-rising-star",
    name: "Botti Bocchetti",
    versionTitle: "天生的巨星",
    sourceShow: "Apollonia",
    score: 3,
    tier: "stable",
    tags: ["stable", "family", "love", "bocchetti"],
    condition: all(min("family", 2), min("love", 1)),
    bondKeys: ["botti-sonny"],
    portraitKey: "botti",
    successText: "Botti 在家族注视下抓住了属于自己的舞台。",
    failureText: "掌声还没响起，家族的阴影先一步落下。",
  },
  {
    id: "luciano-first-godfather",
    name: "Luciano Bocchetti",
    versionTitle: "第一代教父",
    sourceShow: "SantaLucia",
    score: 4,
    tier: "story",
    tags: ["story", "family", "gang", "bocchetti"],
    condition: all(min("family", 2), min("gang", 1)),
    bondKeys: ["luciano-heir"],
    portraitKey: "luciano-young",
    successText: "Luciano 的名字重新压过了赌场里的喧哗。",
    failureText: "旧时代的教父没有等到足够的拥护。",
  },
  {
    id: "luca-soldier",
    name: "Luaco",
    versionTitle: "沉默的士兵",
    sourceShow: "SantaLucia",
    score: 2,
    tier: "stable",
    tags: ["stable", "gang"],
    condition: all(min("gang", 2), min("family", 1)),
    portraitKey: "luca",
    successText: "Luaco 站在门边，替家族挡住了麻烦。",
    failureText: "混乱尚未成形，士兵只能继续等待命令。",
  },
  {
    id: "gambino-rival-boss",
    name: "Gambino",
    versionTitle: "对手家族老大",
    sourceShow: "SantaLucia",
    score: 4,
    tier: "story",
    tags: ["story", "gang", "gamble"],
    condition: all(min("gang", 2), min("gamble", 1)),
    portraitKey: "gambino",
    successText: "Gambino 把谈判桌变成了新的战场。",
    failureText: "对手家族的筹码没能凑齐。",
  },
  {
    id: "chichi-hidden-heir",
    name: "Chichi Bocchetti",
    versionTitle: "阴影里的继承人",
    sourceShow: "SantaLucia",
    score: 4,
    tier: "story",
    tags: ["story", "family", "gang", "bocchetti"],
    condition: all(min("family", 1), min("gang", 1), max("love", 1)),
    bondKeys: ["chichi-sonny", "returned-shadow"],
    portraitKey: "chichi-young",
    successText: "Chi Chi 把不甘藏进了家族的枪声里。",
    failureText: "太多柔软的旧梦让他的狠心动摇了。",
  },
  {
    id: "sonny-legalization",
    name: "Sonnyboy Bocchetti",
    versionTitle: "上院议员",
    sourceShow: "SantaLucia",
    score: 4,
    tier: "story",
    tags: ["story", "family", "gang", "stage", "bocchetti"],
    condition: all(min("family", 1), min("gang", 1), min("stage", 1)),
    bondKeys: [
      "botti-sonny",
      "chichi-sonny",
      "luciano-heir",
      "sonny-two-faces",
      "florence-sonny",
    ],
    portraitKey: "sonny-young",
    successText: "Sonny Boy 把家族故事包装成了体面的未来。",
    failureText: "合法化的剧本缺了最关键的一页。",
  },
  {
    id: "unknown-rich-father",
    name: "富家女的父亲",
    versionTitle: "固执的父亲",
    sourceShow: "Apollonia",
    score: 3,
    tier: "stable",
    tags: ["stable", "family", "gamble", "outsider"],
    condition: all(min("family", 1), min("gamble", 1), max("love", 2)),
    portraitKey: "rich-girl-father",
    successText: "父亲把爱情拦在门外，账本仍然完整。",
    failureText: "年轻人的传说越过了他的门槛。",
  },
  {
    id: "michele-paulo-troubadours",
    name: "Michele & Paulo",
    versionTitle: "赌场主理人",
    sourceShow: "SantaLucia",
    score: 3,
    tier: "stable",
    tags: ["stable", "stage", "bar", "performer"],
    condition: all(min("stage", 2), min("bar", 1)),
    portraitKey: "michele-paulo",
    successText: "歌声把酒馆里的尴尬变成了热闹。",
    failureText: "没有舞台，也没有听众愿意停下脚步。",
  },
  {
    id: "florence-angel-sister",
    name: "Florence",
    versionTitle: "天使姐姐",
    sourceShow: "SantaLucia",
    score: 3,
    tier: "stable",
    tags: ["stable", "love", "family", "outsider"],
    condition: all(min("love", 1), min("family", 1), max("gang", 2)),
    bondKeys: ["stevie-florence"],
    portraitKey: "florence",
    successText: "Florence 站在 Sonnyboy 身旁，让家族的体面多了一点温柔。",
    failureText: "家族和枪声太近，天使姐姐没有等到安稳的位置。",
  },
  {
    id: "florence-pizza-muse",
    name: "Florence",
    versionTitle: "披萨灵感来源",
    sourceShow: "Apollonia",
    score: 5,
    tier: "fate",
    tags: ["fate", "love", "bar", "outsider"],
    condition: all(min("love", 2), min("bar", 1), max("gang", 1)),
    bondKeys: ["florence-sonny"],
    portraitKey: "florence",
    successText: "Florence 成了披萨香气里的灵感，也成了 Stevie 不敢说出口的名字。",
    failureText: "酒馆还在忙乱，灵感没有变成可以端上桌的答案。",
  },
  {
    id: "natalia-fire",
    name: "Natalia",
    versionTitle: "双枪夫人",
    sourceShow: "SantaLucia",
    score: 3,
    tier: "stable",
    tags: ["stable", "family", "love", "bocchetti"],
    condition: all(min("family", 2), min("love", 1), max("gang", 2)),
    portraitKey: "natalia",
    successText: "Natalia 在家族和爱情之间保住了自己的位置。",
    failureText: "火焰太旺，连旧情也被烧成灰。",
  },
  {
    id: "police-chief-compromise",
    name: "警察厅长",
    versionTitle: "调查金条真相",
    sourceShow: "Apollonia",
    score: 4,
    tier: "story",
    tags: ["story", "gang", "gamble"],
    condition: all(min("gang", 1), min("gamble", 1), min("family", 1)),
    portraitKey: "police-chief",
    successText: "警徽和筹码在同一张桌上达成了默契。",
    failureText: "这次交易缺少能让双方点头的价码。",
  },
  {
    id: "rich-girl-runaway",
    name: "富家女",
    versionTitle: "消失在桥头",
    sourceShow: "Apollonia",
    score: 4,
    tier: "story",
    tags: ["story", "love", "family", "outsider"],
    condition: all(min("love", 2), max("gang", 1)),
    bondKeys: ["rich-girl-poor-boy"],
    portraitKey: "rich-girl",
    successText: "她把家族的安排留在身后，奔向自己的传说。",
    failureText: "枪声和流言让这段爱情停在原地。",
  },
  {
    id: "poor-boy-kitchen",
    name: "穷小子",
    versionTitle: "厨房里的披萨",
    sourceShow: "Apollonia",
    score: 3,
    tier: "stable",
    tags: ["stable", "love", "bar", "outsider"],
    condition: all(min("love", 2), min("bar", 1)),
    bondKeys: ["rich-girl-poor-boy"],
    portraitKey: "poor-boy",
    successText: "厨房的热气里，他终于等到了回应。",
    failureText: "锅炉还在响，桥上的约定却没有出现。",
  },
  {
    id: "stevie-manuscript",
    name: "Stevie",
    versionTitle: "灵魂写手",
    sourceShow: "Apollonia",
    score: 3,
    tier: "stable",
    tags: ["stable", "stage", "family", "performer"],
    condition: all(min("stage", 2), min("family", 1)),
    bondKeys: ["stevie-richard", "stevie-florence"],
    portraitKey: "stevie",
    successText: "Stevie 把混乱整理成了可以上演的故事。",
    failureText: "素材满地都是，却拼不出一段可信的叙述。",
  },
  {
    id: "wanderer-rescue",
    name: "流浪汉",
    versionTitle: "巷尾的意外",
    sourceShow: "SantaLucia",
    score: 4,
    tier: "story",
    tags: ["story", "bar", "gang", "outsider"],
    condition: all(min("bar", 1), min("gang", 1), max("gamble", 2)),
    portraitKey: "wanderer",
    successText: "巷尾的醉汉掐住了少年的喉咙。",
    failureText: "赌场的喧哗盖过了那声救命的提醒。",
  },
  {
    id: "luciano-old-door",
    name: "Luciano Bocchetti",
    versionTitle: "老门之后",
    sourceShow: "Apollonia",
    score: 5,
    tier: "fate",
    tags: ["fate", "family", "gang", "bocchetti"],
    condition: all(min("family", 2), min("gang", 1), last("family")),
    bondKeys: ["luciano-heir"],
    portraitKey: "luciano-old",
    successText: "最后出现的仍是家族，旧门再次打开。",
    failureText: "门后没有等来家族的回声。",
  },
  {
    id: "oscar-duet",
    name: "Oscar",
    versionTitle: "掌声搭档",
    sourceShow: "Apollonia",
    score: 2,
    tier: "stable",
    tags: ["stable", "stage", "love", "performer"],
    condition: all(min("stage", 2), min("love", 1)),
    bondKeys: ["richard-oscar"],
    portraitKey: "oscar",
    successText: "Oscar 的节拍接住了台上的尴尬。",
    failureText: "没有灯光，也没有人愿意合拍。",
  },
  {
    id: "richard-drunk-door",
    name: "Richard",
    versionTitle: "醉酒撞门",
    sourceShow: "SantaLucia",
    score: 3,
    tier: "stable",
    tags: ["stable", "stage", "bar", "performer"],
    condition: all(min("stage", 1), min("bar", 2)),
    bondKeys: ["richard-oscar", "stevie-richard"],
    portraitKey: "richard",
    successText: "Richard 撞开了门，也接下了新的工作机会。",
    failureText: "赌场还没营业，醉意只剩狼狈。",
  },
  {
    id: "british-merchant-return",
    name: "英国富商",
    versionTitle: "伦敦归人",
    sourceShow: "SantaLucia",
    score: 4,
    tier: "story",
    tags: ["story", "gamble", "love", "outsider"],
    condition: all(min("gamble", 1), min("love", 1), max("gang", 1)),
    portraitKey: "british-merchant",
    successText: "富商带着账本和悔意回到了故事中央。",
    failureText: "黑帮的气味太重，他选择停在门外。",
  },
  {
    id: "mc-warmup",
    name: "MC",
    versionTitle: "气氛制造者",
    sourceShow: "Apollonia",
    score: 2,
    tier: "stable",
    tags: ["stable", "stage", "performer"],
    condition: all(min("stage", 2), min("bar", 1)),
    portraitKey: "mc",
    successText: "MC 把冷场变成了下一幕的开端。",
    failureText: "没有舞台，主持人也只能收起笑容。",
  },
  {
    id: "botti-gold-secret",
    name: "Botti Bocchetti",
    versionTitle: "罗密欧与朱丽叶",
    sourceShow: "Apollonia",
    score: 4,
    tier: "story",
    tags: ["story", "family", "gamble", "bocchetti"],
    condition: all(min("family", 1), min("gamble", 1), min("bar", 1)),
    bondKeys: ["botti-sonny"],
    portraitKey: "botti",
    successText: "Botti 终于找到了父亲藏起的筹码。",
    failureText: "保险箱还在，但密码没有浮出水面。",
  },
  {
    id: "richard-lonely-dream",
    name: "Richard",
    versionTitle: "舞台中央",
    sourceShow: "Apollonia",
    score: 6,
    tier: "fate",
    tags: ["fate", "stage", "bar", "performer"],
    condition: all(min("stage", 2), min("bar", 1), max("love", 0)),
    bondKeys: ["richard-oscar", "stevie-richard"],
    portraitKey: "richard",
    successText: "舞台亮起时，Richard 只听见自己的回声。",
    failureText: "旧梦里还有别人，他没有真正孤身登台。",
  },
  {
    id: "oscar-future-fiance",
    name: "Oscar",
    versionTitle: "未婚夫",
    sourceShow: "Apollonia",
    score: 4,
    tier: "story",
    tags: ["story", "stage", "love", "performer"],
    condition: all(min("stage", 2), min("love", 1)),
    bondKeys: ["richard-oscar"],
    portraitKey: "oscar",
    successText: "Oscar 把玩笑说成了近在眼前的未来。",
    failureText: "掌声不够，承诺也没有站稳。",
  },
  {
    id: "sonny-family-price",
    name: "Sonnyboy Bocchetti",
    versionTitle: "继承人的代价",
    sourceShow: "Apollonia",
    score: 6,
    tier: "fate",
    tags: ["fate", "family", "gang", "bocchetti"],
    condition: all(min("family", 2), min("gang", 2), last("gang")),
    bondKeys: ["sonny-two-faces", "florence-sonny"],
    portraitKey: "sonny",
    successText: "水花的声响替 Sonnyboy 写下了代价。",
    failureText: "家族还没逼到必须付账的时刻。",
  },
  {
    id: "chichi-returned-truth",
    name: "Chichi Bocchetti",
    versionTitle: "归来的真相",
    sourceShow: "SantaLucia",
    score: 6,
    tier: "fate",
    tags: ["fate", "family", "gang", "stage", "bocchetti"],
    condition: all(min("family", 2), min("gang", 1), min("stage", 2)),
    bondKeys: ["returned-shadow"],
    portraitKey: "chichi-young",
    successText: "真相没有名字，却借 Chichi 的影子回到台前。",
    failureText: "故事讲到一半，最关键的人仍未现身。",
  },
  {
    id: "natalia-mother-line",
    name: "Natalia",
    versionTitle: "家族母亲",
    sourceShow: "SantaLucia",
    score: 3,
    tier: "stable",
    tags: ["stable", "family", "love", "bocchetti"],
    condition: all(min("family", 2), min("love", 1)),
    portraitKey: "natalia",
    successText: "不生了再也不生了。",
    failureText: "家族还在场，却没有足够的温情连接彼此。",
  },
  {
    id: "gambino-casino-trap",
    name: "Gambino",
    versionTitle: "赌场陷阱",
    sourceShow: "SantaLucia",
    score: 4,
    tier: "story",
    tags: ["story", "gang", "gamble"],
    condition: all(min("gamble", 2), min("gang", 1)),
    portraitKey: "gambino",
    successText: "轮盘停下时，Gambino 已经收紧了网。",
    failureText: "筹码散得太开，陷阱没有合拢。",
  },
  {
    id: "stevie-staged-truth",
    name: "Stevie",
    versionTitle: "不能说的真相",
    sourceShow: "Apollonia",
    score: 4,
    tier: "story",
    tags: ["story", "stage", "family", "performer"],
    condition: all(min("stage", 2), min("family", 1), last("stage")),
    bondKeys: ["stevie-richard"],
    portraitKey: "stevie",
    successText: "最后落下的是舞台，Stevie 把故事伪装成了真相。",
    failureText: "谢幕前，真相还没有被排练完成。",
  },
  {
    id: "poor-boy-bridge",
    name: "穷小子",
    versionTitle: "桥上的约定",
    sourceShow: "Apollonia",
    score: 5,
    tier: "fate",
    tags: ["fate", "love", "bar", "outsider"],
    condition: all(min("love", 2), min("bar", 1), max("gang", 0)),
    bondKeys: ["rich-girl-poor-boy"],
    portraitKey: "poor-boy",
    successText: "没有枪声追来，桥上的约定终于成立。",
    failureText: "家族命运追上了他们。",
  },
];
